controller_list:
  - name: fake_all links_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
  - name: fake_griiper_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_5
initial:  # Define initial robot poses per group
  - group: all links
    pose: based